{% set name = "voila-gridstack" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4c25b6cdb1566adac4b7f2387d635d4a6adb01ae53e5d7eba161068c1a72525

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - voila >=0.1.6,<0.2

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/gridstack/nbconvert_templates/voila.tpl"

about:
  home: https://github.com/voila-dashboards/voila-gridstack
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Gridstack template for voila'

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
    - maartenbreddels
