{% set name = "voila-gridstack" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7b15668934337e39bd84f99feb6e44b1dc23e440f28844ce0e307caf7b7b461a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - nodejs =16
    - pip
    - hatchling >=1.4
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - jupyterlab =3.1
  run:
    - python >=3.6
    - voila >=0.2.0,<0.4
    - jupyterlab_widgets >=3.0.0,<4.0.0

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/gridstack/index.html.j2"
    - test -f "${PREFIX}/share/jupyter/labextensions/@voila-dashboards/jupyterlab-gridstack/package.json"
    - test -f "${PREFIX}/share/jupyter/nbextensions/voila-gridstack/extension.js"

about:
  home: https://github.com/voila-dashboards/voila-gridstack
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Gridstack template for Voilà

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
    - maartenbreddels
    - jtpio
    - hbcarlos
