{% set name = "voila-gridstack" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8513b6fb6bb8f7ccec0e0679c234ebc338e86b4f5c4785370387703c88e44ddb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - voila >=0.1,<0.2

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/gridstack/nbconvert_templates/voila.tpl"

about:
  home: https://github.com/QuantStack/voila-gridstack
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Gridstack template for voila'

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
    - maartenbreddels
    
